[tools]
bat = "0.26.1"
bottom = "0.12.3"
delta = "0.18.2"
eza = "0.23.4"
fd = "10.3.0"
fzf = "0.67.0"
gh = "2.86.0"
neovim = "0.11.6"
ripgrep = "15.1.0"
usage = "2.18.0"
zellij = "0.43.1"

[settings]
idiomatic_version_file_enable_tools = []
